apiVersion: v1
kind: Service
metadata:
  name: {{ include "mycedrive.fullname" . }}
  labels:
    {{- include "mycedrive.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
      protocol: TCP
      name: server
  selector:
    {{- include "mycedrive.selectorLabels" . | nindent 4 }}
  # publishNotReadyAddresses allows agents to connect immediately
  publishNotReadyAddresses: true
